services:
  dns:
    image: buscoveanuvictor/dns:staging
    container_name: dns
    ports:
      - "53:53/udp"
    cap_add:
      - NET_BIND_SERVICE
    restart: unless-stopped

  app:
    image: buscoveanuvictor/flask_app:latest
    container_name: app
    hostname: app
    ports:
      - "5000:5000"
    networks:
      - my_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my_network

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  my_network:
    driver: bridge