services:
  dns:
    container_name: dns
    build: 
      context: .
      dockerfile: ./Dockerfile/Dockerfile.dns
    ports:
      - "53:53/udp"
    cap_add:
      - NET_BIND_SERVICE
    restart: unless-stopped

  api:
    container_name: api
    hostname: api
    build: 
      context: .
      dockerfile: ./Dockerfile/Dockerfile.api
    ports:
      - "5000:5000"
    networks:
      - my_network

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my_network

networks:
  my_network:
    driver: bridge