services:
  dns:
    container_name: dns
    build: 
      context: .
      dockerfile: Dockerfile.dns
    ports:
      - "53:53/udp"
    cap_add:
      - NET_BIND_SERVICE
    restart: unless-stopped
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5000:5000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge