apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      location / {
        proxy_pass http://app:8081;
      }
    }
    