name: Build and Push Docker Images

on:
  push:
    branches:
      - staging 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push API image
      - name: Build and push API image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/flask_api:staging \
            -f ./Dockerfile/Dockerfile.api \
            --push .

      # Build and push DNS image
      - name: Build and push DNS image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/dns:staging \
            -f ./Dockerfile/Dockerfile.dns \
            --push .

  