name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Rulează workflow-ul doar pe push în branch-ul `main`

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push API image
      - name: Build and push API image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask_api:latest -f ./Dockerfile/Dockerfile.api .
          docker push ${{ secrets.DOCKER_USERNAME }}/flask_api:latest

      - name: Build and push DNS image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dns:latest -f ./Dockerfile/Dockerfile.dns .
          docker push ${{ secrets.DOCKER_USERNAME }}/dns:latest

  